"""empty message

Revision ID: 4629bac4ccb7
Revises: 36364a61d402
Create Date: 2014-08-18 19:54:01.804000

"""

# revision identifiers, used by Alembic.
revision = '4629bac4ccb7'
down_revision = '36364a61d402'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_image', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_image')
    ### end Alembic commands ###
